Pachkoriya_HW09/Models/Bus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pachkoriya_HW09.Models
{
    public class Bus
    {
        // гос. номер 
        [Required(ErrorMessage = "Обязательно к заполнению")]
        [StringLength(25, ErrorMessage = "Длина имени не более 10 символов")]
        [Display(Name = "Государственный номер")]
        public string GovernmentNumber { get; set; }

        // маршрут
        [Required(ErrorMessage = "Обязательно к заполнению")]
        [StringLength(25, ErrorMessage = "Длина имени не более 50 символов")]
        [Display(Name = "Маршрут")]
        public string Route { get; set; }

        // фамилия и инициалы водителя
        [Required(ErrorMessage = "Обязательно к заполнению")]
        [StringLength(25, ErrorMessage = "Длина имени не более 10 символов")]
        [Display(Name = "Фамилия и инициалы водителя")]
        public string Driver { get; set; }

        // количество мест
        [Range(20, 50, ErrorMessage = "Количество мест должно быть в диапазоне от 20 до 50")]
        [Display(Name = "Количество мест")]
        public int SeatsNumber { get; set; }

        // стоимость билета
        [Range(250, 10000, ErrorMessage = "Стоимость билета должна быть в диапазоне от 250 до 10000")]
        [Display(Name = "Цена билета")]
        public double TicketPrice { get; set; }
        // список пассажиров
        public List<Passenger> Passengers { get; set; }
        // общий вес пассажиров
        public int TotalWeight() => Passengers.Sum(x => x.Weight);
        // общий процент заполненности автобуса
        public string TotalPersent() => $"{Passengers.Count / (double)SeatsNumber * 100d:n2}";
        // общая стоимость проданных билетов
        public string TotalCost() => $"{Passengers.Count * TicketPrice}";
        // сортировка по номеру места
        public List<Passenger> SortPassengersBySeatNumber() => Passengers.OrderBy(x => x.SeatNumber).ToList();
        // сортировка по фамилии и инициалам
        public List<Passenger> SortPassengersBySurnameNP() => Passengers.OrderBy(x => x.SurnameNP).ToList();

        // добавить пассажира
        public void AddPassenger(Passenger passenger)
        {
            passenger.SeatNumber = Passengers.Max(p => p.SeatNumber) + 1;
            Passengers.Add(passenger);
        } // AddPassenger

        // удалить пассажира
        public void DelPassenger(Passenger passenger) => Passengers.Remove(passenger);
    }
}

Pachkoriya_HW09/Models/BusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pachkoriya_HW09.Models
{
    public class BusViewModel
    {
        public Bus Bus { get; set; }
        public bool SortPassengersBySeatNum { get; set; }
        public bool SortPassengersBySurnameNP { get; set; }
    }
}

Pachkoriya_HW09/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pachkoriya_HW09.Models;

namespace Pachkoriya_HW09.Controllers
{
    public class BusController : Controller
    {
        private BusRepository _busRepository;

        public BusController(BusRepository busRepository)
        {
            _busRepository = busRepository;
        } // BusController

        // GET: BusController
        public ActionResult Index()
        {
            return View();
        }

        // Вывести данные автобуса и список пассажиров по номеру места
        public IActionResult SortPassengersBySeatNumber()
            => View();

        // Вывести данные автобуса и список пассажиров в алфавитном порядке
        public IActionResult SortPassengersBySurnameNP()
            => View();

        public IActionResult AddPassenger()
        {
            return View();
        } // AddPassenger

        [HttpPost]
        [ValidateAntiForgeryToken]
        // Добавить пассажира
        public IActionResult AddPassenger(Passenger passenger)
        {
            if (ModelState.IsValid)
            {
                _busRepository.Bus.AddPassenger(passenger);
                _busRepository.SerializeBus();
                return RedirectToAction("Index");
            }
            
            return View(passenger);
        } // AddPassenger

        // GET: BusController/Edit/5
        public ActionResult EditBus()
        {
            if (_busRepository.Bus == null)
            {
                return View("Error");
            }
            return View(_busRepository.Bus);
        }

        // POST: BusController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBus(Bus bus)
        {
            try
            {
                _busRepository.EditBus(bus);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(bus);
            }
        }

        // GET: BusController/Delete/5
        public ActionResult DeleteQuestion(Passenger passenger) => View(passenger);

        // POST: BusController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePassenger(int seatNumber)
        {
            Passenger passenger = _busRepository.Bus.Passengers.First(x => x.SeatNumber == seatNumber);
            _busRepository.Bus.DelPassenger(passenger);
            _busRepository.SerializeBus();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult TestError()
        {
            throw null;
            return View();
        }
    }
}

Pachkoriya_HW09/Views/Bus/AddPassenger.cshtml
@model Pachkoriya_HW09.Models.Passenger
@{
    ViewData["Title"] = "Добавление нового пассажира";
}

<main class="container">
    <section class="row">
        <article class="offset-1 col-10 bg-light">
            <br />
            <form asp-action="AddPassenger">
                <h2 class="text-center">Добавить пассажира:</h2>
                <br />
                <span asp-validation-for="SurnameNP" class="text-danger"></span><br />
                <div class="input-group mb-3 text-center">
                    <div class="input-group-prepend">
                        <label asp-for="SurnameNP" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="SurnameNP" class="form-control" />
                </div>
                <span asp-validation-for="BirthYear" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="BirthYear" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="BirthYear" class="form-control" />
                </div>
                <span asp-validation-for="Height" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="Height" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="Height" class="form-control" />
                </div>
                <span asp-validation-for="Weight" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="Weight" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="Weight" class="form-control" />
                </div>
                <br />
                <input class="btn btn-success" type="submit" value="Сохранить" />
                <a class="btn btn-primary float-right" asp-controller="Bus" asp-action="Index">
                    Назад
                </a>
            </form>
            <br />
        </article>
    </section>
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

Pachkoriya_HW09/Views/Bus/DeleteQuestion.cshtml
@model Pachkoriya_HW09.Models.Passenger

@{
    ViewBag.Title = "Удалить";
}

<h3 class="text-center">Вы уверены что хотите удалить пассажира?</h3>
<div>
    <hr />
    <p class="text-justify text-center">
        Фамилия, инициалы: <b>@Model.SurnameNP</b>
    </p>
    <p class="text-justify text-center">
        Год рождения: <b>@Model.BirthYear</b>
    </p>
    <p class="text-justify text-center">
        Рост: <b>@Model.Height</b>
    </p>
    <p class="text-justify text-center">
        Вес: <b>@Model.Weight</b>
    </p>
    <p class="text-justify text-center">
        Место: <b>@Model.SeatNumber</b>
    </p>
    <form asp-action="DeletePassenger" asp-route-seatNumber="@Model.SeatNumber">
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" />
            <a class="btn btn-primary float-right" asp-controller="Bus" asp-action="Index">
                Назад
            </a>
        </div>
    </form>
</div>

Pachkoriya_HW09/Views/Bus/EditBus.cshtml
@model Pachkoriya_HW09.Models.Bus

@{
    ViewData["Title"] = "Редактировать автобус";
}

<main class="container">
    <section class="row">
        <article class="offset-1 col-10 bg-light">
            <br />
            <form asp-action="EditBus">
                <h2 class="text-center">Редактировать автобус:</h2>
                <span asp-validation-for="GovernmentNumber" class="text-danger"></span><br />
                <div class="input-group mb-3 text-center">
                    <div class="input-group-prepend">
                        <label asp-for="GovernmentNumber" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="GovernmentNumber" value="@Model.TicketPrice" class="form-control" />
                </div>
                <span asp-validation-for="Route" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="Route" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="Route" class="form-control" />
                </div>
                <span asp-validation-for="Driver" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="Driver" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="Driver" class="form-control" />
                </div>
                <span asp-validation-for="SeatsNumber" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="SeatsNumber" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="SeatsNumber" class="form-control" />
                </div>
                <span asp-validation-for="TicketPrice" class="text-danger"></span><br />
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label asp-for="TicketPrice" class="input-group-text" id="inputGroup-sizing-default"></label>
                    </div>
                    <input asp-for="TicketPrice" class="form-control" />
                </div>
                <br />
                <input class="btn btn-success" type="submit" value="Сохранить" />
                <a class="btn btn-primary float-right" asp-controller="Bus" asp-action="Index">
                    Назад
                </a>
            </form>
            <br />
        </article>
    </section>
</main>

Pachkoriya_HW09/Views/Bus/Index.cshtml
@using Pachkoriya_HW09.Components;
@{
    ViewData["Title"] = "Автобус";
}

<main class="container">
    <section class="row">
        <article class="offset-1 col-10 bg-light">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-primary" asp-controller="Bus" asp-action="SortPassengersBySeatNumber">
                    Упорядочивание пассажиров по номеру места
                </a>
                <a class="btn btn-primary" asp-controller="Bus" asp-action="SortPassengersBySurnameNP">
                    Упорядочивание пассажиров по фамилиям
                </a>
                <a class="btn btn-primary" asp-controller="Bus" asp-action="AddPassenger">
                    Добавить пассажира
                </a>
                <a class="btn btn-primary" asp-controller="Bus" asp-action="EditBus">
                    Редактировать автобус
                </a>
            </div>
            <br />
            <br />
            <h3 class="text-center text-dark">Данные автобуса</h3>
            <br />
            @await Component.InvokeAsync(nameof(BusData))
        </article>
    </section>
</main>

Pachkoriya_HW09/Views/Bus/SortPassengersBySeatNumber.cshtml
@using Pachkoriya_HW09.Components;

@{
    ViewData["Title"] = "Пассажиры упорядочены по номеру места";
}

<main class="container">
    <section class="row">
        <article class="offset-1 col-10 bg-light">
            <h2 class="text-success text-center">Пассажиры упорядочены по номеру места</h2>
            <a class="btn btn-primary float-right" asp-controller="Bus" asp-action="Index">
                Назад
            </a>
            <br />
            <br />
            <h3 class="text-center text-dark">Данные автобуса</h3>
            <br />
            @await Component.InvokeAsync(nameof(BusData), new { sortPassengersBySeatNum = true })
        </article>
    </section>
</main>

Pachkoriya_HW09/Views/Bus/SortPassengersBySurnameNP.cshtml
@using Pachkoriya_HW09.Components;

@{
    ViewData["Title"] = "Пассажиры упорядочены по фамилиям";
}

<main class="container">
    <section class="row">
        <article class="offset-1 col-10 bg-light">
            <h2 class="text-success text-center">Пассажиры упорядочены по фамилиям и инициалам</h2>
            <a class="btn btn-primary float-right" asp-controller="Bus" asp-action="Index">
                Назад
            </a>
            <br />
            <br />
            <h3 class="text-center text-dark">Данные автобуса</h3>
            <br />
            @await Component.InvokeAsync(nameof(BusData), new { sortPassengersBySurnameNP = true })
        </article>
    </section>
</main>

Pachkoriya_HW09/Views/Bus/TestError.cshtml
@{
    ViewData["Title"] = "Тест ошибки";
}

<body>
    <h2>Тест ошибки</h2>
</body>